name: ci

on:
  push:
    branches: master

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to YC
        uses: docker/login-action@v1
        with:
          registry: yc.io
          username: oauth
          password: AQAAAAA0Nm7zAATuwRYE2Y4geEtzhLbafnw6d4M
    name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: user/app:latest
